### ISSUE TITLE
test pools created

### ISSUE THREAD

**Issue by sponnet** [frens-pool/frens-dapp#92]
pool2 : https://goerli.explorer.ssv.network/validators/ab427a2a14d2a2d5e6c77af44ff189931c679b2b4235219923d4d38aaa7a2f8269f4826b234d236a82fea75b406c8d76

has "invalid key"

pool1: 
https://goerli.explorer.ssv.network/validators/805b157228bc5f2e8f63f86877dd67b16db64abe7153282aaec7c742eb0c6329f6e1dfb7094a0d0f8ec8f06e3200f84b

looks OK

**Comment by normadn** [comment]
https://goerli.explorer.ssv.network/validators/a20ba758ca2d77fb7d171fa02898ef0d0d4c3243b41369bc05b42947447548707c0d52470f916bf750b57979138c889e

this is also invalid?!

**Comment by normadn** [comment]
fixed that. We had the wrong ssv nonce.
